import Footer from "@/component/layout/Footer";
import Navbar from "@/component/layout/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const georgia = localFont({
  src: [
    {
      path: "./font/georgia.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/georgiab.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./font/georgiai.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./font/georgiaz.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-georgia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${georgia.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
